### ISSUE TITLE
Major lack of library functions documentation

### ISSUE THREAD

**Issue by CaveJohnson376** [OttoDIY/OttoDIYLib#28]
To begin with, i work as course planning helper at robotics club, and i've got task to help preparing part of course that involves using Otto robots (we did not ordered them from OttoDIY tho, we have made our own kits using lasercut plywood and other components ordered from China). After some research, i found this library, but i found no proper documentation/description of all or, at least, most functions available. This is bad, as not everyone will be able to see that easily, what functions they can use, what parameters they have to pass, how it all works in general. If Otto is intended to be robotics programming educational platform, then there should be at least some function description readily available either there on github, or on website (or on both).

If there is some actual documentation available, then please, post a link somewhere so people can easily find it, or point me to it, i'll be thankful

Thanks in advance

**Comment by cparrapa** [comment]
Hi @CaveJohnson376 

Good to know we thought the description was good enough for github users, the libraries themselves are fill with comments and explanations https://github.com/OttoDIY/OttoDIYLib/blob/master/Otto.cpp 

We always intended this repo for intermediate/advanced coding and Otto Blockly is more for beginners which I advice you to look at and its pretty much self explanatory with the block functions parallel to text based coding.

Nevertheless we have bunch of guides in our website https://www.ottodiy.com/academy, you might need to dig deep for this very specific functions you are asking, if there is something specifically missing, let me know or you can propose directly as a PR in a better readme, since it seems you are "good at debug and writing READMEs"

Thanks and welcome to the community
