### ISSUE TITLE
Other Otto Robots BLE App Code

### ISSUE THREAD

**Issue by Trajectory989** [OttoDIY/OttoDIYLib#32]
Hello,

Per the powerpoints and things on the website, there used to be code available for all the different robots to be controlled via bluetooth at one point in the past (i.e. it has listed different bluetooth programs such as OttoW_APP as an example program that used to be provided by this library which I simply take to mean there was a version of app code that worked with Otto Wheels).

What happened? Now everything runs off of the Otto object defined in Otto.h and Otto.cpp which clearly only corresponds to the original Otto Starter. Whatever happened that got rid of these entirely?

**Comment by cparrapa** [comment]
Hi @Trajectory989 
Yes we used to have that but for the arduino Libraries manager we simplify as much as possible the codes so that you can always add up libraries according to your robot or simply use Otto Blockly that comes with all of them pre installed.

The code you are looking for is attached here https://builders.ottodiy.com/question/hello-every-one-i-have-a-problem-with-my-otto-wheels-when-i-connect-it-with--624d6be139e578407e798ec4 but it was not perfect code so work needs to be done there

Only one we get some help on how to unify have a modular code so that is versatile for all the robots we cant have them all here because it was creating confusion on people and bad compilations or not working properly
